---
title: "kevinMarkdown"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2018 Apr 02, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Loading packages
```{r}
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(ggiraph)
```

# Loading functions
```{r}
theme_set(theme_classic(18) +
            theme(legend.position = 
                    "bottom"))
```


# Loading data
```{r}
raw_data = readxl::read_excel(here("2018-04-02", "us_avg_tuition.xlsx"), sheet = 1)
```


# Data cleaning 
```{r}
long_data = raw_data %>% 
  tidyr::gather(key = year, 
                value = cost, 
                -State)

long_data
```


# Data summaries
```{r}
long_data %>% 
  dplyr::filter(year == "2004-05") %>% 
  dplyr::arrange(cost)
```


# Data visulisation

## Time line
```{r}
long_data %>% 
  ggplot(aes(x = year, y = cost, 
             group = State,
             colour = State)) +
  geom_path() +
  theme(legend.position = "none")
```





# Add in US regions data
```{r}
region_data = read_csv(here("2018-04-02", "US_state_regions.csv"), 
                       col_names = c("Region", "State")) %>% 
  tidyr::fill(Region, .direction = "down") %>% 
  dplyr::mutate(State = str_trim(State, side = "right"))

region_data

```







# Add in the GDP data from Wikipedia

```{r}
us_states_gdp = read_csv(here("2018-04-02", "us_states_GDP_PerCap.csv")) %>% 
  dplyr::select(-Rank) %>% 
  tidyr::gather(key = year, 
                value = gdp,
                -State)

us_states_gdp
```


## Checking state labels
```{r}
gplots::venn(
  list(
    tuition_data = long_data$State %>% unique,
    gdp_data = us_states_gdp$State %>% unique, 
    region_data = region_data$State %>% unique
  )
)
```

## Merging data

```{r}
long_data_merge = long_data %>% 
  dplyr::mutate(
    year_range = year, 
    year = stringr::str_sub(year, 1L, 4L))

merge_data = long_data_merge %>% 
  dplyr::left_join(us_states_gdp, by = c("State", "year")) %>% 
  dplyr::left_join(region_data, by = "State")
```

## Visualisation of GDP and cost

```{r}
complete_merge_data = merge_data %>% 
  dplyr::filter(complete.cases(gdp)) %>% 
  dplyr::group_by(year) %>% 
  dplyr::mutate(
    rank_gdp = rank(-gdp), 
    rank_cost = rank(-cost),
    cost_gdp_ratio = cost/gdp) %>% 
  ungroup()

complete_merge_data %>% 
  ggplot(aes(x = gdp, y = cost, colour = Region)) +
  ggiraph::geom_point_interactive(aes(tooltip = State, onclick = rank_gdp, data_id = State)) +
  ggsci::scale_color_lancet() +
  scale_y_continuous(labels = scales::dollar) +
  scale_x_continuous(labels = scales::dollar) +
  facet_grid(year ~ Region) +
  labs(title = "Tuition cost vs GDP per cap, per US state", 
       x = "GDP per cap (USD)", 
       y = "Tuition cost (USD)") +
  theme_bw(18) +
  theme(legend.position = "bottom")


plot_merge_2011 = complete_merge_data %>% 
  dplyr::filter(year == 2011) %>% 
  ggplot(aes(x = gdp, y = cost, colour = Region)) +
  ggiraph::geom_point_interactive(aes(tooltip = State, onclick = rank_gdp, data_id = State)) +
  ggsci::scale_color_lancet() +
  scale_y_continuous(labels = scales::dollar) +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "2011: Tuition cost vs GDP per cap, per US state", 
       x = "GDP per cap (USD)", 
       y = "Tuition cost (USD)")

plot_merge_2015 = complete_merge_data %>% 
  dplyr::filter(year == 2015) %>% 
  ggplot(aes(x = gdp, y = cost, colour = Region)) +
  ggiraph::geom_point_interactive(aes(tooltip = State, onclick = rank_gdp, data_id = State)) +
  ggsci::scale_color_lancet() +
  scale_y_continuous(labels = scales::dollar) +
  scale_x_continuous(labels = scales::dollar) +
  labs(title = "2015: Tuition cost vs GDP per cap, per US state", 
       x = "GDP per cap (USD)", 
       y = "Tuition cost (USD)")

cowplot::plot_grid(plot_merge_2011 +
                     ggpubr::stat_conf_ellipse(aes(color = Region), level = 0.8), 
                   plot_merge_2015 +
                     ggpubr::stat_conf_ellipse(aes(color = Region), level = 0.8))

```

https://cran.r-project.org/web/packages/ggsci/vignettes/ggsci.html

## Interactive plot 
```{r}
girafe(code = print(plot_merge_2011 + plot_merge_2015), width_svg = 8, height_svg = 4)
```


# Time series plot of GDP and Tuition 

```{r}
cost_gather_gdp_data = complete_merge_data %>% 
  ungroup() %>% 
  tidyr::gather(key = key, 
                value = value, 
                cost, gdp) %>% 
   dplyr::mutate(
     key = dplyr::case_when(
    key == "gdp" ~ "GDP per cap", 
    key == "cost" ~ "Tuition cost"
  ))


cost_gather_gdp_data %>% 
  ggplot() +
  geom_path(aes(x = year, y = value, colour = Region, group = State), 
            alpha = 0.3) +
  stat_summary(aes(x = year, 
                   y = value, 
                   colour = Region, 
                   group = Region),
               fun.y = "median", size = 2, geom = "path") +
  facet_wrap(~key, nrow = 1, scales = "free_y") +
  scale_y_continuous(labels = scales::dollar, breaks = c(5000, 7500, 10000, 12500, 15000, (3:7)*10000)) +
  ggsci::scale_color_d3() +
  labs(title = "Tuition cost and GDP per cap, per US Region", 
       x = "Year", 
       y = "") +
  theme_classic(18) +
  theme(legend.position = "bottom", 
    plot.title = element_text(hjust = 0.5), 
    panel.grid.major.x = element_blank())



complete_merge_data %>% 
  dplyr::mutate(Region = fct_reorder(Region, cost_gdp_ratio, .fun = median)) %>% 
  ggplot(aes(x = year, y = cost_gdp_ratio)) +
  geom_path(aes(colour = Region, group = State)) +
  facet_wrap(Region~., nrow = 1)


tuition_gdp_ratio_plot = complete_merge_data %>% 
  dplyr::mutate(Region = fct_reorder(Region, cost_gdp_ratio, .fun = median)) %>% 
  ggplot() +
  geom_path(aes(x = year, y = cost_gdp_ratio, colour = Region, group = State), 
            alpha = 0.5) +
  stat_summary(aes(x = year, 
                   y = cost_gdp_ratio, 
                   colour = Region, 
                   group = Region),
               fun.y = "median", size = 2, geom = "path") +
  facet_wrap(~Region, nrow = 1) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +
  ggsci::scale_color_d3() +
  labs(title = "Tuition cost - GDP per cap ratio, per US Region", 
       x = "Year", 
       y = "Tuition cost - GDP per cap ratio") +
  theme_classic(18) +
  theme(legend.position = "bottom", 
    plot.title = element_text(hjust = 0.5), 
    panel.grid.major.x = element_blank(), 
    axis.text.x = element_text(angle = 90))

tuition_gdp_ratio_plot


ggsave(filename = here("2018-04-02", "tuition_gdp_ratio_plot.png"), 
       plot = tuition_gdp_ratio_plot, 
       width = 15, height = 6)


saveRDS(complete_merge_data, file = here("2018-04-02", "complete_merge_data.RDS"))
```



# Session Info
```{r}
sessionInfo()
```

